  init_state:
    pos: [0.0, 0.0, 0.8] # x,y,z [m]
    rot: [0.0, 0.0, 0.0, 1.0] # x,y,z,w [quat] 
    lin_vel: [0.0, 0.0, 0.0]  # x,y,z [m/s]
    ang_vel: [0.0, 0.0, 0.0]  # x,y,z [rad/s]
    default_joint_angles: # = target angles [rad] when action = 0.0
      left_hip_pitch_joint: -0.1
      left_hip_roll_joint: 0.
      left_hip_yaw_joint: 0.
      left_knee_joint: 0.3
      left_ankle_pitch_joint: -0.2
      left_ankle_roll_joint: 0.
      right_hip_pitch_joint: -0.1
      right_hip_roll_joint: 0.
      right_hip_yaw_joint: 0.
      right_knee_joint: 0.3
      right_ankle_pitch_joint: -0.2
      right_ankle_roll_joint: 0.
      waist_yaw_joint : 0.
      waist_roll_joint : 0.
      waist_pitch_joint : 0.
      left_shoulder_pitch_joint: 0.2
      left_shoulder_roll_joint: 0.2
      left_shoulder_yaw_joint: 0.
      left_elbow_joint: 0.9
      right_shoulder_pitch_joint: 0.2
      right_shoulder_roll_joint: -0.2
      right_shoulder_yaw_joint: 0.
      right_elbow_joint: 0.9
      left_wrist_roll_joint: 0.
      left_wrist_pitch_joint: 0.
      left_wrist_yaw_joint: 0.
      right_wrist_roll_joint: 0.
      right_wrist_pitch_joint: 0.
      right_wrist_yaw_joint: 0.



  control:
    control_type: P
    # PD Drive parameters:
    stiffness: # [N*m/rad]
      hip_yaw: 100
      hip_roll: 100
      hip_pitch: 100
      knee: 150
      ankle_pitch: 40
      ankle_roll: 40
      waist_yaw: 400
      waist_roll: 400
      waist_pitch: 400
      shoulder_pitch: 100
      shoulder_roll: 100
      shoulder_yaw: 50
      elbow: 50
      wrist: 10


    damping: # [N*m/rad]  # [N*m*s/rad]
      hip_yaw: 2.0
      hip_roll: 2.0
      hip_pitch: 2.0
      knee: 4.0
      ankle_pitch: 2.0
      ankle_roll: 2.0
      waist_yaw: 5.0
      waist_roll: 5.0
      waist_pitch: 5.0
      shoulder_pitch: 2.0
      shoulder_roll: 2.0
      shoulder_yaw: 2.0
      elbow: 2.0
      wrist: 0.1